### ISSUE TITLE
Add LDC support

### ISSUE THREAD

**Issue by TiberiumPY** [kingsleyh/DLanguage#108]
I was surpired when I saw it - DLanguage plugin doesn't support other compilers!

**Comment by SingingBush** [comment]
If you are using dub then it's possible to configure it to use LDC.

<img width="970" alt="screen shot 2016-10-11 at 09 36 01" src="https://cloud.githubusercontent.com/assets/870567/19263868/54b776d8-8f96-11e6-943b-179d9964084c.png">
