### ISSUE TITLE
Incorrect  directories in ExecUtil.java

### ISSUE THREAD

**Issue by pirocks** [kingsleyh/DLanguage#109]
lines 136-139:
            `paths.add(homeDir + sep + "Library" + sep + "Haskell" + sep + "bin");`
            `paths.add(homeDir + sep + ".cabal" + sep + "bin");`
            `paths.add(sep + "usr" + "local" + sep + "bin");`
            `paths.add(homeDir + sep + "bin");`

Seems like this is intended for Haskell not D.

**Comment by kingsleyh** [comment]
Hey - I probably stole some code from the Haskell plugin and didn’t get around to refactoring it very much.

There are a probably a few places like this - and also from the Dart plugin and a few others.
—K

**Comment by SingingBush** [comment]
this was fixed in https://github.com/kingsleyh/DLanguage/commit/6d4cf6a48ee70997e0185032b81eda15c63a6103
