### ISSUE TITLE
Write access is allowed from write-safe contexts only.

### ISSUE THREAD

**Issue by OrionCrim** [kingsleyh/DLanguage#116]
I just updated my IntelliJ version to 2016.3.1 from 2016.1.x where the plugin worked fine.  I'm receiving a notification of "IDE Errors", the "details" link reveals the following messages in the "IDE Fatal Errors" dialog:

> Error message:
> Write access is allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
> 
> Details:
> Write access is allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
>   current modality=ModalityState.NON_MODAL
>   known modalities={ModalityState.NON_MODAL=true}
> java.lang.Throwable
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
> 	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:246)
> 	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:296)
> 	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:288)
> 	at net.masterthought.dlanguage.highlighting.annotation.external.DExternalAnnotator$1.run(DExternalAnnotator.java:48)
> 	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:166)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:417)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by kingsleyh** [comment]
Thanks for reporting - we will be releasing a new version that works with the latest IntelliJ versions soon

**Comment by SingingBush** [comment]
this has already been fixed in master. see issue #113 

@kingsleyh it's probably worth doing a tag for version 1.11 now and getting it into the repo. If there's any further compatibility issues I can pick them up this week.
