### ISSUE TITLE
Exception: "Write access is allowed from write-safe contexts only"

### ISSUE THREAD

**Issue by FatalCatharsis** [kingsleyh/DLanguage#119]
When I created a new D project and then added a new D file, the IDE produced this stack trace.

https://gist.github.com/FatalCatharsis/5889077ce28deae8656d03090bcf81af

(Edit: it also appears that the "source" directory created automatically at the root of my project is not visible to the project. http://imgur.com/a/ASFpI)

(Edit 2: closing and re-importing the project resolved the issue, but I will leave this here in case you can reproduce it. I do however still receive the original exception when opening any file in the project so it must not have been related.)

**Comment by pirocks** [comment]
I to have experienced this issue. When editing the D files that are part of this plugins test suite.

**Comment by tmarsteel** [comment]
Just got that error, too. Happened when i opened a file from an imported dub project.

**Comment by SingingBush** [comment]
this has been fixed in master. Just needs a new build. Until there's a new build in the plugin repo you could clone the project and build the master branch.
