### ISSUE TITLE
Importing a freshly created dub project does not work.

### ISSUE THREAD

**Issue by SjoerdNijboer** [kingsleyh/DLanguage#122]
When creating a new dub project with 'dub init stuff' (format: json) and then importing it using start intellij-> import project -> /folder/path/to/stuff/ -> import model from external model -> dub -> auto find -> finish.
The application hangs on the startup screen.

dub:  1.1.2.
compiler: dmd 2.072.2
idea: 2016.3.2 community
dlanguage: 1.10
os: windows 10 x64

**Comment by SingingBush** [comment]
I think this was an issue with compatibility that's now fixed in latest build.

https://github.com/kingsleyh/DLanguage/releases

should be in plugin repo soon. please test and let us know if there's still a problem
