### ISSUE TITLE
When generated code is regenerated via ctrl+shift+g Types in DLanguageTypes are missing

### ISSUE THREAD

**Issue by pirocks** [kingsleyh/DLanguage#125]
When the code in gen/ is regenerated the DLanguageTypes class is missing these static members:
`IElementType KEYWORD = new DLanguageElementType("KEYWORD");`
 ` IElementType OPERATOR = new DLanguageElementType("OPERATOR");`
`  IElementType NUMBER = new DLanguageElementType("NUMBER");`
`  IElementType STRING = new DLanguageElementType("STRING");`
`  IElementType PARENTHESES = new DLanguageElementType("PARENTHESES");`
`  IElementType BRACES = new DLanguageElementType("BRACES");`
`  IElementType BRACKETS = new DLanguageElementType("BRACKETS");`
`  IElementType COMMA = new DLanguageElementType("COMMA");`
`  IElementType SEMICOLON = new DLanguageElementType("SEMICOLON");`
 ` IElementType DOT = new DLanguageElementType("DOT");`
 ` IElementType MODULE_DEFINITION = new DLanguageElementType("MODULE_DEFINITION");`
`  IElementType FUNCTION_DEFINITION = new DLanguageElementType("FUNCTION_DEFINITION");`

**Comment by kingsleyh** [comment]
I was originally using the same lexer for the language and for the syntax highlighting - but I saw another plugin using a dedicated lexer for syntax highlighting so I switched to doing that thinking I would be able to get more detailed highlighting - however after I talked to the author he was going to back it out and use the single lexer as he didn't gain anything from it. I realised he is right and we should move back to using the one lexer for both. But I haven't had time to make those changes.

**Comment by pirocks** [comment]
So for now I/We should just copy paste these types in every time the main parser and lexer are regenerated?

**Comment by kingsleyh** [comment]
yes for now till we get rid of the other lexer

**Comment by pirocks** [comment]
Ok. Closing then. Have you seen my pr?
