### ISSUE TITLE
Is it possible to debug code?

### ISSUE THREAD

**Issue by Stretto** [kingsleyh/DLanguage#130]
I built all the dependencies and was able to get all the basics working but I haven't been able to debug a test project. I assume this functionality is not included... is there any way to get debugging working?

**Comment by kingsleyh** [comment]
Hi - sorry there's no debugger support yet - you would have to debug from the command line or something

**Comment by Stretto** [comment]
Could something like the mago debugger that Visual D uses not be used? How hard would it be to connect them?

**Comment by kingsleyh** [comment]
It looks hard to connect them - also it looks like mago only runs on windows - I don't own any windows machines

**Comment by pirocks** [comment]
I do own a windows machine, and might make a debugger at some point. Specifically when resolve is improved, and when the bnf grammar parses the standard library correctly.

**Comment by kingsleyh** [comment]
A cross platform debugger would be nice

**Comment by SingingBush** [comment]
will keep #106 open for debugger related stuff
