### ISSUE TITLE
IDEA still showing 1.10

### ISSUE THREAD

**Issue by russel** [kingsleyh/DLanguage#138]
The JetBrains repository still only has version 1.10.

**Comment by russel** [comment]
Can 1.11 and 1.12 be uploaded?

**Comment by kingsleyh** [comment]
I have uploaded them both - Jetbrains need to review them within 2 business days before they go public

**Comment by SingingBush** [comment]
These are now showing in [Jetbrains repo](https://plugins.jetbrains.com/plugin/8115-d-language?pr=idea) website but the download option is still pending. Once they are available it's probably worth posting in https://forum.dlang.org/group/announce

**Comment by russel** [comment]
1.12 appears to be available via the repository now so I am closing this issue.

Can we change develop to 1.13-SNAPSHOT?

**Comment by SingingBush** [comment]
yeah, develop should be 1.13-SNAPSHOT. I'll push it in a min
