### ISSUE TITLE
Import Dub project appears to fail

### ISSUE THREAD

**Issue by russel** [kingsleyh/DLanguage#141]
Using IDEA 2017.1 with DLanguage plugin compiled from master/HEAD as at 2017-03-23T09:26+01:00 10db13ddb4de6e5a94172731b5a67acf0d336e77 I tried importing a project from existing sources, and that seemed to work except that the source and test-source directories were not flagged as sources and tests. I guess there is a convention for these directories different from this.

I then tried importing the same project as a Dub project; there is a dub.sdl file. I got the dialogue asking for the location of the dub executable pressing "auto" finds the right executable, press finish… and nothing back to the main "no open project" window.

**Comment by SingingBush** [comment]
I'm not sure if .sdl is supported. issue #86 was never done. If you have time can you quickly check if this works when the dub file is json. if so we can close this. I think the sdl support is a feature that can be worked on for future release.

**Comment by kingsleyh** [comment]
Hi

I think sdl is not supported only json

**Comment by russel** [comment]
Take the issue of #86 to there.

**Comment by russel** [comment]
Moved the dub.sdl file aside, created a dub.json file, but got the same result. having set the path to dub, nothing further happens.

**Comment by russel** [comment]
Because there was a syntax error in the dub.json file. :-(  Fix the error fix the problem. Project now imports.

Should the Dub error be reported rather than seemingly ignored?

**Comment by SingingBush** [comment]
yeah there is a mechanism in intellij for showing problems like that to the user. is that something you can pick up?

**Comment by russel** [comment]
I'll see what I can do.

**Comment by SingingBush** [comment]
btw, for this I think you'll need `com.intellij.notification.Notifications.Bus.notify()` with `com.intellij.notification.NotificationType`

**Comment by SingingBush** [comment]
@russel did you get anywhere with this? I've been doing work on tool window that needed some changes to _DubConfigurationParser_ so I'll be pushing some changes (soon) to develop that will possibly fix this.

**Comment by russel** [comment]
@SingingBush I haven't had change I'm afraid, ACCUConf stuff and preparing for JAXFinance got in the way, amongst other things. It will be a couple of weeks before I can get onto anything. Sorry.

**Comment by SingingBush** [comment]
ok cheers. I'm pretty sure #150 resolves this so closing

**Comment by russel** [comment]
I have opened #152 to deal with the leftovers of this issue not solved by #150.
