### ISSUE TITLE
Weird (?) warning in Kotlin task of build 

### ISSUE THREAD

**Issue by russel** [kingsleyh/DLanguage#143]
I see:
```
:compileTestKotlin
w: The '-d' option with a directory destination is ignored because '-module' is specified
```
Clearly not a problem per se, but why is this reported?

**Comment by SingingBush** [comment]
may be this: 
https://discuss.kotlinlang.org/t/kotlin-1-1-0-gradle-compile-warning/2360

**Comment by russel** [comment]
I guess wait for 1.1.2 and see if it goes away.

**Comment by SingingBush** [comment]
It's probably worth trying this with Kotlin 1.1.2-eap-44

**Comment by SingingBush** [comment]
Kotlin 1.1.2 is out so I tried it out and it does resolve the issue
