### ISSUE TITLE
improve DubConfigurationParser and add tests

### ISSUE THREAD

**Issue by SingingBush** [kingsleyh/DLanguage#150]
the _DubConfigurationParser_ runs `dub describe` to import dub projects (so dub.json or dub.sdl is fine). The way it currently handles io from the command is less than ideal as it doesn't differentiate between stdout and stderr. Also, there properties that don't actually make there way to _DubPackage_

I've made some changes that will make it easier to detect problems when importing a dub project as well as making use of some of the other fields.

Also there were no tests for the parser so I've included all the dub.sdl files from the vibe-d project as test resources as they're a pretty good test case. It means that travis will need to have dub available on the path for the test to pass.

this will probably fix #141 as well

**Comment by SingingBush** [comment]
can ignore test fail on travis. Need to have dmd and dub for the test to pass. It runs fine locally. will sort it when back online, maybe tomorrow.

**Comment by SingingBush** [comment]
travis-ci build is working again. we now have dmd, dub, dcd, dfmt, and dscanner available when running tests.

**Comment by russel** [comment]
Part of #141 does indeed appear to be fixed by this. Opening #152 to deal with the leftovers.
