### ISSUE TITLE
section in README about editing Info.plist

### ISSUE THREAD

**Issue by SingingBush** [kingsleyh/DLanguage#35]
The readme file recommends editing Info.plist to get IDEA to run with Java 7 or 8 on mac. As per info on [JetBrains site](https://intellij-support.jetbrains.com/entries/27854363-IDE-doesn-t-start-after-updating-to-Mac-OS-Yosemite-or-Mavericks):

> Modifying Info.plist will break the application digital signature and prevent the patch updates. We do not recommend modifying Info.plist file to run under JDK 1.7 or 1.8. The recommended way of overriding JDK version via idea.properties file can be found [here](https://youtrack.jetbrains.com/issue/IDEA-126847#comment=27-884634).

**Comment by kingsleyh** [comment]
Thanks for raising this. The jet brains post you referenced is from 2013 - do you think it's still valid? I have had no issues with getting patch updates or had any issues with hanging etc. I use 1.8 with the plist edit. The public end of life for java 1.6 was feb 2013 and we are nearing the 1.7 end of life in april 2015 - so jet brains (and apple) should really try to get themselves up to date!

**Comment by SingingBush** [comment]
I think that section of the post was an edit added at a later date. Even if it wasn't though, there is a comment on Jan 5th this year by Serge (the Jetbrains employee that made the post) that repeats the same info:

> Modifying Info.plist will break application signature, it's expected. We've implemented another way to specify JDK version recently, [check this comment](https://youtrack.jetbrains.com/issue/IDEA-126847#comment=27-884634). See also [this document](https://intellij-support.jetbrains.com/entries/23395793) if you can't find idea.properties file for your product.

I've not updated IDEA in a while so not sure if it is actually a problem but may be worth using the supported method.
