### ISSUE TITLE
BNF grammar/roadmap

### ISSUE THREAD

**Issue by landaire** [kingsleyh/DLanguage#39]
I'm not sure if you'd like to avoid creating a BNF grammar if you can but I think that the current model using `dcd` is sustainable. I may be mistaken but it looks like the [Haskell plugin](https://github.com/Atsky/haskell-idea-plugin) uses a similar model with `ghc-mod` and it seems to work fine. It may be worth looking into.

**Comment by kingsleyh** [comment]
Dcd is fine actually - I already implemented it. The issue is the DTD parser integration with IntelliJ - it's very poor performance - so IntelliJ quickly locks up when writing a long or complex file - and hangs waiting for the parser

--k

**Comment by kingsleyh** [comment]
I have started work on this now - I will completely re-write the plugin using the BNF grammar
