### ISSUE TITLE
creating D project with DUB

### ISSUE THREAD

**Issue by eyveer** [kingsleyh/DLanguage#42]
Choosing create new project, D project with DUB. 
Project is created, there's project.iml and empty "source" dir. I cant just create main.d file and build project because dub throws error:
    Please run DUB from the root directory of an existing package, or run
    "dub init --help" to get information on creating a new package.

and also cant run dub init in this project - "The target directory already contains a 'source/' file. Aborting."

**Comment by kingsleyh** [comment]
Ah ok - I think I know what is causing that I will fix

**Comment by kingsleyh** [comment]
Fixed
