### ISSUE TITLE
autocompletion from dub packages 

### ISSUE THREAD

**Issue by eyveer** [kingsleyh/DLanguage#43]
Could you please instruct me how can set up dcd to make auto complete work with external libraries imported with dub? I tried to set dcd client param -I/home/user/.dub/packages and adding symlinks to libraries inside project dir with no luck.

**Comment by kingsleyh** [comment]
I haven't thought about that yet - but I think it should work by adding the path where the d files live to the client list of imports - I will investigate tomorrow - if you get it working let me know - also check hackerpilots DCD GitHub page for info 

Continue to raise stuff and I will investigate - feature requests also 

--Kingsley

**Comment by kingsleyh** [comment]
I've fixed this and updated README to explain how to use DCD imports
