### ISSUE TITLE
Syntax highlighting for DUB's SDL format

### ISSUE THREAD

**Issue by tsbockman** [kingsleyh/DLanguage#46]
This is not important, but I bet it wouldn't be too hard to add, so I'll look into it.

**Comment by kingsleyh** [comment]
This would be nice - I'm focused on adding things like refactoring tools right now and other main improvements - so this is not high on my list. If you want to contribute something that would be great - this might even be a separate plugin just for SDL support.

**Comment by kingsleyh** [comment]
I can't seem to find a grammar for the SDL - If there was one already ideally in bnf format then it would be quite straightforward to add this - otherwise it would take some time to figure out what the grammar should look like. I can't really find much good documentation for this format either. :(

**Comment by tsbockman** [comment]
Yes, this is a known problem for SDL. It seems the original author may have abandoned it; the homepage has been broken for a while.

The D community may be forced to take over future maintenance and development, if we want to keep using it.

Andrei Alexandrescu has [called for SDL support to be dropped from DUB](http://forum.dlang.org/post/n351uu$a52$1@digitalmars.com) because of its obsucrity; he didn't want it to become a drain on the community's limited resources.

However, a lot of people (including me) dislike JSON and XML, so I think SDL is here to stay. I might take a crack at making an [EBNF](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_Form) grammar for it at some point.

**Comment by russel** [comment]
@tsbockman  What is the path to taking over the SDL project so it becomes supported?

**Comment by SingingBush** [comment]
closing this issue. let's track anything SDL related in #86
