### ISSUE TITLE
DUB init options

### ISSUE THREAD

**Issue by tsbockman** [kingsleyh/DLanguage#47]
* `--format=<value>` to choose between JSON and SDL configuration formats.
* `--type=<value>` to select the project stub type.

**Comment by kingsleyh** [comment]
I will add this in the next release - I think I will add another step to the configure project wizard which asks for the dub init options (after the choose compiler step)

**Comment by tsbockman** [comment]
That would work, although the choose compiler step is mostly empty space as it is, so you could just combine the two.

**Comment by kingsleyh** [comment]
I'm investigating - the compiler step is a built in WizardStep - there are several provided ones - none of them do what I want though - so I think I will have to write a custom one - so to start I think it will be easier to add a new custom one - and then refactor them together later if it makes sense.

**Comment by kingsleyh** [comment]
Added dub init config wizard step to dub module builder - will include in next release
