### ISSUE TITLE
Add DFix option

### ISSUE THREAD

**Issue by kingsleyh** [kingsleyh/DLanguage#48]
add option to run DFix on a file https://github.com/Hackerpilot/dfix

**Comment by tsbockman** [comment]
> dfix will edit your files in-place. Do not use dfix on files that have no backup copies. Source control solves this problem for you. Double-check the results before checking in the modified code.

IntelliJ probably takes care of this automatically, but make sure there is an easy way to undo the DFix operation.

**Comment by kingsleyh** [comment]
done and will be in next release
