### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by russel** [kingsleyh/DLanguage#62]
The front page gives a once installed usage summary (with lots of nice pictures), a summary of how to set up to work on the plugin code, but appears not to give instructions on how to install the plugin either from a repository or from the project. Or am I just missing something?

**Comment by SingingBush** [comment]
It only went into the jetbrains repo a couple of weeks back:

https://plugins.jetbrains.com/plugin/8115?pr=idea

I've done a short blog post about setting it up with DCD, DScanner and Dfmt:

http://www.samael.me.uk/2015/12/d-plugin-for-intellij-idea.html

**Comment by russel** [comment]
Can plugins be removed from the repository? "D Language Support" 0.0.8 is in there and has the potential for detracting the unwary from the real release.

**Comment by kingsleyh** [comment]
yes they can be removed - but only by the account that created it as far as I know

**Comment by kingsleyh** [comment]
updated readme

**Comment by russel** [comment]
I wonder if we can get https://github.com/shekn-itrtch/DLangPlugin and https://plugins.jetbrains.com/plugin/7727?pr=idea to say they are moribund and point at this repository and https://plugins.jetbrains.com/plugin/8115?pr=idea ?
