### ISSUE TITLE
IntelliJ IDEA project files

### ISSUE THREAD

**Issue by russel** [kingsleyh/DLanguage#63]
Is it right that the IntelliJ IDEA control files are in version control. As soon as anyone opens the project large tracts of the files change, also some of the hardwired paths are wrong. This means the control files are always in conflict with the repository. This can lead to problems creating pull requests.

I think it much better to have a Gradle project file (possibly replacing the Ant build) which is in version control, then people can create projects for themselves with all the project files not being in version control and therefore there not being a conflict.

**Comment by kingsleyh** [comment]
I'll have a think about this one.

**Comment by russel** [comment]
As noted on the other issue, I'll take a look at creating a Gradle build. I think IntelliJ IDEA works better with a Gradle build for a project than for an Ant one these days. Can probably only make the decision after showing the ease and efficacy of the alternative.

**Comment by SingingBush** [comment]
closing as this been completed
