### ISSUE TITLE
Binary OR (|) token not recognized

### ISSUE THREAD

**Issue by caspervg** [kingsleyh/DLanguage#65]
Figured I would take a crack at learning D using the new plugin for IntelliJ with the Dlang-Koans. It seems that there is a small issue where the binary or ``|`` token is not properly recognized. Dub is able to compile and run the code without problems, however.

![image](https://cloud.githubusercontent.com/assets/3718739/12209344/90e89dee-b652-11e5-9c43-1fb5b726e98b.png)

The same error message is shown for ``auto x = true | false;`` but not for ``auto x = true & false;``

Latest version of the plugin installed. Installed versions of the supporting tools can be found [here](https://cloud.githubusercontent.com/assets/3718739/12209544/01f2930e-b654-11e5-91cd-9681f7ae17a1.png)

**Comment by kingsleyh** [comment]
Great thanks for spotting it - I will fix it in the next release

**Comment by kingsleyh** [comment]
Fixed and will be in next release
