### ISSUE TITLE
Editor doesn't deal with scripts.

### ISSUE THREAD

**Issue by russel** [kingsleyh/DLanguage#69]
If the first line of a code file starts with a # (for the #! command line of a script), the editor flags this as an error. I guess this is a grammar thing?

**Comment by Hackerpilot** [comment]
This is probably missing from the DLanguage lexer/parser because it's not documented anywhere on dlang.org. In other words, flagging this as an error is correct according to the specification.

**Comment by Hackerpilot** [comment]
https://issues.dlang.org/show_bug.cgi?id=15556

**Comment by kingsleyh** [comment]
Fixed and will be in next release

**Comment by russel** [comment]
Thanks. Looking forward to the update. :-)
