### ISSUE TITLE
auto safe = 1

### ISSUE THREAD

**Issue by trikko** [kingsleyh/DLanguage#79]
```
void test()
{
    auto safe = 1;
}
```

"declaration or storage class expected, got safe"

**Comment by kingsleyh** [comment]
That's weird - it's something to do with the word "safe"!

**Comment by Hackerpilot** [comment]
`@safe` is built-in to the language, `safe` is a normal identifier.

**Comment by Hackerpilot** [comment]
Here's your problem: https://github.com/kingsleyh/DLanguage/blob/master/src/net/masterthought/dlanguage/grammar/DLanguage.bnf#L91

**Comment by kingsleyh** [comment]
ah good spot ! thanks !!!

**Comment by kingsleyh** [comment]
Hackerpilot: Be sure that you also remove "trusted", "system", and "disable"

**Comment by kingsleyh** [comment]
fixed and will be in next release
