### ISSUE TITLE
DCD locks up the editor

### ISSUE THREAD

**Issue by kingsleyh** [kingsleyh/DLanguage#80]
intermittent editor locking up - which seems to be caused by DCD. Restarting the DCD server fixes it. I suspect it's some kind of threading / locking issue that I need to handle correctly in intellij

**Comment by tsbockman** [comment]
I'm also effected by this (or something similar). I ended up just turning DCD off since the IDE is almost unusable otherwise.

**Comment by caspervg** [comment]
I have also experienced this (on Linux). Generally I just restart the IDE and then it will work for a couple of minutes again. I noticed a lot of TCP errors in Wireshark in the connection between dcd-server and the IDE while the lock-up occurs.

**Comment by kingsleyh** [comment]
Fixed I think and will be in next release

**Comment by kingsleyh** [comment]
I've released v1.10 with a fix for DCD locking up the editor - could you verify if you think it's an improvement?

**Comment by tsbockman** [comment]
I downloaded the new version and re-enabled DCD. I'll let you know if I have more problems with it.
